### PR TITLE
Codebase cleanup

### PR DESCRIPTION
**Pull request by sharils**
Feel free to let me know if any of them doesn't make sense. And I'm prepared to drop commits.

> 	@sharils 	sharils 	Fix eslint auto-fixable 			0403860
>	@sharils 	sharils 	Fix no-unused-vars 			fa7a693
>	@sharils 	sharils 	Add jest to eslint env 			f04a1ed
>	@sharils 	sharils 	Add .eslintignore 			2d44929

Because CONTRIBUTING.md says, "Make sure your code lints." And my `` yarn run eslint . `` doesn't pass.

> @sharils 	sharils 	Add jshint to devDependencies 			50cd81f

This one I'm not sure whether I should add jshint to devDependencies or delete .jshintrc. So I just choose an arbitrary one.

### CODE REVIEW

**Comment by fkling** [comment]
Thank you! The `.jshint` file should simply be removed since it's not used.

**Comment by sharils** [comment]
Hi @fkling 

> Thank you! The .jshint file should simply be removed since it's not used.

No problem! I've just dropped that commit and added another commit to remove the `` .jshintrc `` file.

**Comment by sharils** [comment]
Hi @fkling , would you mind taking another look at this PR? Thanks. :)

**Comment by sharils** [comment]
Hi @cpojer - Would you mind taking a look at this PR? I really would like this to be merged. Thanks.

**Comment by cpojer** [comment]
Sure, works for me.

**Pull request merged**
