### PR TITLE
Consider the case where there's only 1 CPU

### LINKED ISSUE #136: Spawning 0 Workers - jscodeshift doesn't run in an environment with 1 CPU
When running a codemod (lodash-codemods in particular), I see it finds files but then spawns 0 workers. 
Looking at the source code I believe it caused by this line: https://github.com/facebook/jscodeshift/blob/e03140df04c9914680b860209ed118fc7d9a8cba/src/Runner.js#L24
I'm running this in a docker container which only has 1 CPU - running `require('os').cpus()` in node in the same place returns an array with a single CPU, but `length - 1` in an environment like mine with 1 CPU will prevent it from running. Does jscodeshift simply require multiple CPUs, or can we change this behavior (with a flag or otherwise)?

### PR DESCRIPTION
**Pull request by daedalus28**
Should fix #136

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by daedalus28** [comment]
Just signed the CLA

**Comment by Daniel15** [comment]
What about `Math.max(require('os').cpus().length - 1, 1)`? I think it captures the intent better.

**Comment by daedalus28** [comment]
Works for me, just made the change. Pretty excited to get this merged :+1:

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by fkling** [comment]
That was quick, thank you! I will look at the other PRs today and will try to get a new version out today.

Thank you again!

**Comment by daedalus28** [comment]
Awesome, glad to have this fixed :smile:

**Pull request merged**
