### PR TITLE
Add support for arrays to replaceWith, insertBefore and insertAfter.

### PR DESCRIPTION
**Pull request by cpojer**
I've been working around this in my codemods so far, this makes it so that you can pass an array to these methods (or return an array from the replacer method). I also removed `functionify` and inlined it.

I also added tests for insertAfter.

### CODE REVIEW

**Comment by fkling** [comment]
lgtm... seems like call spread is already supported?

**Comment by cpojer** [comment]
Jest has trouble with the jscodeshift-test in `bin`. Not sure what is going on, do you have an idea? It also happens locally. And yeah, call spread is supported in babel.

**Comment by fkling** [comment]
Will have to look into it when I'm back but looks like the jest issue we still haven't fixed.

But you are not using Babel ;)

**Comment by fkling** [comment]
Updated for latest master.

**Pull request merged**
