### PR TITLE
Respect extensions cli option when filtering individual files

### PR DESCRIPTION
**Pull request by robcmills**
Resolves https://github.com/facebook/jscodeshift/issues/561

### CODE REVIEW

**Comment by Daniel15** [comment]
This could go either way - it's not defined whether passing in an exact filename should bypass the extension filter or not. Changing it so everything observes the extension filter seems reasonable to me though.

**Comment by lg-kialo** [comment]
> This could go either way - it's not defined whether passing in an exact filename should bypass the extension filter or not. Changing it so everything observes the extension filter seems reasonable to me though.

@Daniel15 I disagree, for a single filename supplying the extension twice (once in the filename and once as `--extension` flag) seems redundant.

**Comment by Daniel15** [comment]
@lg-kialo The `--extension` flag is optional. You don't have to provide it.

**Comment by lg-kialo** [comment]
@Daniel15 you do have to provide it if you want to transform files with extension different than `.js`.
Before version 0.15.1 `jscodeshift -t transform.ts fileToTransform.tsx` used to work, now one is forced to use `jscodeshift -t transform.ts --extensions=tsx fileToTransform.tsx`

**Comment by lg-kialo** [comment]
My suggestion would be that if no `--extensions` flag is passed, we don't filter by extension at all. Instead of filtering only files with the default extension (`.js`) as it is now.

**Pull request merged**
