### PR TITLE
chore(dev-deps): bump jest to v29

### PR DESCRIPTION
**Pull request by chimurai**
fixed breaking changes introduced in v27: https://jestjs.io/blog/2021/05/25/jest-27#miscellaneous-breaking-changes
fixed snapshot format in v29: https://jestjs.io/blog/2022/08/25/jest-29

### CODE REVIEW

**Comment by chimurai** [comment]
CI will fail due to unsupported node12 in jest29.

CI fix: https://github.com/facebook/jscodeshift/pull/530 (drop node12, add node18 support)

**Comment by Daniel15** [comment]
Could you please rebase now that I've merged #530?

**Comment by chimurai** [comment]
Rebased 👍

**Comment by Daniel15** [comment]
Thanks :)

**Pull request merged**
