### PR TITLE
Bump micromatch from 3.1.10 to 4.0.4

### PR DESCRIPTION
**Pull request by trivikr**
Refs https://github.com/facebook/jscodeshift/issues/490

### CODE REVIEW

**Comment by Daniel15** [comment]
Since this is a major version bump, is the API the same, or could this result in a change in behaviour?

**Comment by trivikr** [comment]
> Since this is a major version bump, is the API the same, or could this result in a change in behaviour?

I'm not sure. 

Since jscodeshift is going to be active again as per https://github.com/facebook/jscodeshift/issues/482#issuecomment-1078546582, we should switch to GitHub Actions and ensure CI is run before merging any existing PRs. WDYT?

**Comment by Daniel15** [comment]
> we should switch to GitHub Actions and ensure CI is run before merging any existing PRs. WDYT?

This sounds great!

**Comment by trivikr** [comment]
PR added to enable GitHub Actions in https://github.com/facebook/jscodeshift/pull/493

**Comment by trivikr** [comment]
> Since this is a major version bump, is the API the same, or could this result in a change in behaviour?

The only API used in jscodeshift is `isMatch()`, and it's not changed as per CHANGELOG
https://github.com/micromatch/micromatch/blob/master/CHANGELOG.md#400---2019-03-20

https://github.com/facebook/jscodeshift/blob/4a3db92cada44768f3eeada496ba24985deec8d4/src/ignoreFiles.js#L62

> We should switch to GitHub Actions and ensure CI is run before merging any existing PRs.

This PR was rebased after CI was enabled in https://github.com/facebook/jscodeshift/pull/493, and CI is successful.

**Comment by Daniel15** [comment]
Sounds good to me!

**Comment by dartess** [comment]
@trivikr npm still has an old version of micromatch:

```
{
  "name": "jscodeshift",
  "version": "0.13.1",
  "description": "A toolkit for JavaScript codemods",
  "repository": {
    "type": "git",
    "url": "https://github.com/facebook/jscodeshift.git"
  },
  "bugs": "https://github.com/facebook/jscodeshift/issues",
  "main": "index.js",
  "scripts": {
    "prepare": "cp -R src/ dist/",
    "test": "jest --bail",
    "docs": "rm -rf docs && jsdoc -d docs -R README.md src/collections/* src/core.js src/Collection.js"
  },
  "bin": {
    "jscodeshift": "./bin/jscodeshift.js"
  },
  "keywords": [
    "codemod",
    "recast",
    "babel"
  ],
  "author": "Felix Kling",
  "license": "MIT",
  "dependencies": {
    "@babel/core": "^7.13.16",
    "@babel/parser": "^7.13.16",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.13.8",
    "@babel/plugin-proposal-optional-chaining": "^7.13.12",
    "@babel/plugin-transform-modules-commonjs": "^7.13.8",
    "@babel/preset-flow": "^7.13.13",
    "@babel/preset-typescript": "^7.13.0",
    "@babel/register": "^7.13.16",
    "babel-core": "^7.0.0-bridge.0",
    "chalk": "^4.1.2",
    "flow-parser": "0.*",
    "graceful-fs": "^4.2.4",
    "micromatch": "^3.1.10",
    "neo-async": "^2.5.0",
    "node-dir": "^0.1.17",
    "recast": "^0.20.4",
    "temp": "^0.8.4",
    "write-file-atomic": "^2.3.0"
  },
  "peerDependencies": {
    "@babel/preset-env": "^7.1.6"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "eslint": "^5.9.0",
    "jest": "^21",
    "jsdoc": "^3.4.0",
    "mkdirp": "^0.5.1"
  },
  "jest": {
    "roots": [
      "src",
      "bin",
      "parser",
      "sample"
    ]
  }
}
```

Could you post a fresh package version to npm?

**Comment by trivikr** [comment]
> Could you post a fresh package version to npm?

I'm just a contributor, and don't have maintainer privileges.
@ElonVolo would be the lead for this project as per discussions in https://github.com/facebook/jscodeshift/issues/482

**Comment by Daniel15** [comment]
I can do this today.

**Comment by dartess** [comment]
It seems that they forgot about the publication of the update again :(

@Daniel15 or @ElonVolo friendly ping

**Comment by janpe** [comment]
@Daniel15 @ElonVolo is there a chance of getting this bump in a new release?

**Comment by ElonVolo** [comment]
I’m a Facebook employee so I do not have npm publish superpowers. We’ll have to tap @Daniel15 on the shoulder for that 😄

**Comment by janpe** [comment]
@ElonVolo do you happen to know if there is someone else who can publish since Daniel doesn't seem to be responsive at the moment?

**Comment by Daniel15** [comment]
I'm so sorry about this! Stuff came up in my personal life that meant I couldn't push the package on August 10th. This was on my todo list but I completely forgot about it. :(

I'm working on it right now.

**Comment by Daniel15** [comment]
@janpe @dartess @trivikr @ElonVolo  I've just published the new package to npm. I'm having trouble pushing the tag to this repo but I'll do that soon too.

**Comment by janpe** [comment]
@Daniel15 thank you very much! I hope things are getting better for you. Take care!

**Comment by rarenatoe** [comment]
I'm still experimenting this issue despite updating react-native to 0.70.3
```
└─ my-project@workspace:.
   └─ react-native@npm:0.70.3 [fceeb] (via npm:0.70.3 [fceeb])
      ├─ @react-native-community/cli@npm:9.1.3 (via npm:9.1.3)
      │  └─ @react-native-community/cli-plugin-metro@npm:9.2.1 (via npm:^9.1.3)
      │     ├─ metro-config@npm:0.72.3 (via npm:0.72.3)
      │     │  └─ metro@npm:0.72.3 (via npm:0.72.3)
      │     │     ├─ metro-config@npm:0.72.3 (via npm:0.72.3)
      │     │     └─ metro-file-map@npm:0.72.3 (via npm:0.72.3)
      │     │        └─ micromatch@npm:4.0.5 (via npm:^4.0.4)
      │     └─ metro@npm:0.72.3 (via npm:0.72.3)
      └─ react-native-codegen@npm:0.70.6 (via npm:^0.70.5)
         └─ jscodeshift@npm:0.13.1 [75b54] (via npm:^0.13.1 [75b54])
            └─ micromatch@npm:3.1.10 (via npm:^3.1.10)
```

**Comment by stianjensen** [comment]
> I'm still experimenting this issue despite updating react-native to 0.70.3

I created a PR for that now:
https://github.com/facebook/react-native/pull/35356

**Pull request merged**
