### PR TITLE
Replace deprecated babel-preset-2015 with babel-preset-env

### PR DESCRIPTION
**Pull request by oculus42**
Replaces `babel-preset-2015` with `babel-preset-env`, [as recommended](http://babeljs.io/env).

Relates to #222 and #246

### CODE REVIEW

**Comment by TheAifam5** [comment]
If you don't like the warning messages, please add this to your `package.json`:
```
"resolutions": {
    "webpack-cli/**/jscodeshift": "facebook/jscodeshift#247/head"
  },
```

**Comment by stof** [comment]
@fkling is there any plan to merge this ?

**Comment by Tiendq** [comment]
It takes too much time to upgrade this package? I still see the warning now :(

`warning webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!`

**Comment by AliSawari** [comment]
@oculus42 so you mean, this PR will be merged once the Bable 7 stable version releases?

**Comment by oculus42** [comment]
@AliSawari I'm hoping this gets merged before that, as this solves a current problem.

**Comment by edmorley** [comment]
Just to clarify - there is no need to use the Babel 7 version of preset-env (and therefore have to wait for Babel 7 final). 

The deprecation warning comes from use of  babel-preset-es2015, which is the predecessor to the Babel 6 babel-preset-env.

**Comment by oculus42** [comment]
Updated to resolve the `yarn.lock` conflict after the 0.5.1 patch.

**Comment by DanieleGBX** [comment]
What's currently holding this from being merged?

**Comment by oculus42** [comment]
Nothing of which I am aware. Perhaps @fkling or @cpojer can shed some light on that?

**Comment by andresroberto** [comment]
@fkling @cpojer would be nice to have this merged 😄if you find it's fine

**Comment by regrettably** [comment]
Is this ever going to get merged?

**Comment by milesj** [comment]
Babel 7 has been released now, so the entire Babel suite should also be upgraded.

**Comment by bsotodo** [comment]
any news on this?

**Comment by fkling** [comment]
These packages have been updated.

**Pull request closed without merging**
