### PR TITLE
binary file name changed

### PR DESCRIPTION
**Pull request by udnisap**

### CODE REVIEW

**Comment by fkling** [comment]
yeah, that makes more sense, however I think this could potentially be a breaking change, so I will leave this till the next breaking version.

**Comment by udnisap** [comment]
@fkling I think this is not a breaking change as the updated version will use the updated package.json which has the correct link

**Comment by Daniel15** [comment]
Is this still an issue?

**Comment by ElonVolo** [comment]
There don't seem to be any other complaints about this in 7 years or so since the PR was submitted. The context is so old at this point it's probably just worth closing.

**Pull request closed without merging**
