### PR TITLE
Add recipe for retaining leading comment in first statement within file

### PR DESCRIPTION
**Pull request by DrewML**
[Reference](https://github.com/facebook/jscodeshift/issues/44#issuecomment-227315386).

Open to feedback on the example/verbiage/etc 😃

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by DrewML** [comment]
I think @facebook-github-bot-8 [hates me](https://github.com/facebook/jscodeshift/pull/118#issuecomment-226900561) 😄

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by fkling** [comment]
But @facebook-github-bot-5 loves you ;) Thanks, will take a look soon!

**Comment by fkling** [comment]
lgtm... thank you again! Lets hope we will get more soon :)

**Comment by DrewML** [comment]
😃 @fkling I'll keep an eye on open issues to see if more questions popup that can be added. Looking for ways to contribute while I get used to the codebase.

**Pull request merged**
