### PR TITLE
Replace "babel-preset-es2015" with "babel-preset-env"

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves https://github.com/facebook/jscodeshift/issues/222

/cc @hzoo

### CODE REVIEW

**Comment by Turbo87** [comment]
@fkling got time for a quick review?

**Comment by Turbo87** [comment]
feel free to reopen whenever you find the time to review this

**Comment by fernandopasik** [comment]
@cpojer or @fkling would it be possible to reopen and get reviewed this one? thanks!

**Comment by gpnoel** [comment]
@cpojer or @fkling another bump. Or just an update to the situation itself?

**Comment by hulkish** [comment]
+1

**Comment by WilliamNovak** [comment]
+1

**Comment by f3l1x** [comment]
:+1:

**Pull request closed without merging**
