### PR TITLE
Replace deprecated nomnom

### LINKED ISSUE #170: Deprecated dependency: nomnom
As of Sep 9, 2015, [nomnom](https://github.com/harthur/nomnom) has been marked as deprecated. The author recommends switching to [commander.js](https://github.com/tj/commander.js).

### PR DESCRIPTION
**Pull request by dhruvdutt**
image

Replaces deprecated [nomnom](https://github.com/harthur/nomnom) with an [active published fork](https://www.npmjs.com/package/@gerhobbelt/nomnom) to remove the deplication warning.

> @cpojer @fkling Kindly requesting a review, merge & release of this? A reasonably large number of dependencies 'lying in wait'. thx!

Fixes #170, [#287](https://github.com/webpack/webpack-cli/issues/287)

### CODE REVIEW

**Comment by dhruvdutt** [comment]
@cpojer @fkling 
Can you please review?

**Comment by ev1stensberg** [comment]
This would break a lot of packages that depend on `jscodeshift` once it is removed

**Comment by hulkish** [comment]
@ev1stensberg how so?

**Comment by ev1stensberg** [comment]
Might be my interpretation, but once a package is depreciated, then it's going to be removed at some point in future.

**Comment by hulkish** [comment]
@ev1stensberg I think I misunderstood your comment... I read it as if you were saying this PR was going to break downstream (Which I think now we both agree is not true). Glad that's cleared up, lol.

**Comment by ev1stensberg** [comment]
Haha sorry! Was in a different context!

**Comment by ematipico** [comment]
Conflicts :(

**Comment by dhruvdutt** [comment]
@ematipico Resolved conflicts. :v:

**Comment by celeduc** [comment]
Merge and release? Please?

**Comment by ematipico** [comment]
Any news here?

**Comment by fkling** [comment]
I went with implementing our own version (a2becc5cf9263c3fe675218e059a181c35ce7060).

**Pull request closed without merging**
