### PR TITLE
use babel parser for recast parsing - fixes #14

### LINKED ISSUE #14: Use Babel's parser instead of recast's default parser (esprima-fb)

### PR DESCRIPTION
**Pull request by hzoo**
#14 

I ~~can* also~~ added another commit to also use babel for build/watch and remove react-tools

### CODE REVIEW

**Comment by hzoo** [comment]
I guess the issue is with jest/jsdom/contextify? https://github.com/facebook/jest/issues/243 - tests pass on node 0.10

**Comment by cpojer** [comment]
Awesome.

We should probably upgrade to io.js.

@fkling now that babel has become the de-facto standard, should we just run the transform file through babel as well? Best case users of jscodeshift don't need their own wrapper library (like I build), worst case we transform a file twice, which shouldn't be a big deal.

**Comment by benjamn** [comment]
+1 to switching to the Babel parser for everything. Recast can parse/visit/print all the types it uses.

**Comment by fkling** [comment]
@cpojer: Sure. Maybe we can add a flag that disables transpilation (I *think* Babel has (had) some issues with double compilation).
@hzoo: can you have a look why Travis fails? Do the tests pass locally?

**Comment by hzoo** [comment]
@fkling Yeah made a comment above

> I guess the issue is with jest/jsdom/contextify? facebook/jest#243 - tests pass on node 0.10

It's working locally for me on node v0.10.38 (ubuntu).

**Comment by fkling** [comment]
Yeah, I missed that comment... strange though, because Travis also fails for v0.10, which seems to indicate that it is not a jest problem?

**Comment by hzoo** [comment]
Ok I just cleared my npm cache and did npm install again and have 3 local tests failing too now...

**Comment by hzoo** [comment]
Weird getting a syntax error

```text
FAIL  src/__tests__/core-test.js
SyntaxError: /home/henry/Dev/jscodeshift/src/__tests__/core-test.js:
/home/henry/Dev/jscodeshift/src/core.js:
/home/henry/Dev/jscodeshift/node_modules/babel-core/index.js:
... a lot more  babel files
/home/henry/Dev/jscodeshift/node_modules/babel-core/node_modules/is-integer/node_modules/is-nan/node_modules/define-properties/node_modules/object-keys/index.js:
Unexpected identifier
    at Contextify.sandbox.run (/home/henry/Dev/jscodeshift/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify/lib/contextify.js:12:24)
    at JSDomEnvironment.runSourceText (/home/henry/Dev/jscodeshift/node_modules/jest-cli/src/JSDomEnvironment.js:111:22)
```

**Comment by hzoo** [comment]
@fkling @benjamn Has no one used babel/acorn with recast yet? If not, then think it's because it's not compatible with esprima? In `babel-eslint` we've had to do make a https://github.com/babel/babel-eslint/blob/master/acorn-to-esprima.js. by convert acorn tokens to esprima somewhat compatible. Although I guess that wouldn't be why there's an syntax error - will check it out more later

**Comment by cpojer** [comment]
Been trying to get this to work to no avail so far. Ugh.

**Comment by hzoo** [comment]
:disappointed: I tried iojs@2.3.4 with nvm and facebook/jest#0.5.x and got the same kind of syntax error (and this is with no other changes like using babel)

```
 FAIL  src/collections/__tests__/JSXElement-test.js
SyntaxError: /home/henry/Dev/jscodeshift/src/collections/__tests__/JSXElement-test.js: Unexpected identifier
  at Object.exports.runInContext (vm.js:43:16)
  at JSDomEnvironment.runSourceText (/home/henry/Dev/jscodeshift/node_modules/jest-cli/src/JSDomEnvironment.js:110:8)
```

**Comment by fkling** [comment]
Just to establish a baseline: I can run the tests on the master branch without problems on Node v0.10.36.

**Pull request closed without merging**
