### PR TITLE
Allow transform to be a promise. Resolves #210.

### LINKED ISSUE #210: Allow returning a Promise?
I'm trying to write a codemod that opens tickets for each TODO or FIXME in my code and updates the in-code comments to include the link to the ticket. As far as I can tell, that's currently impossible given jscodemod's API is synchronous.

Is there a way to do this now? If not, would you be open to a PR that allows the transform function to return a Promise?

### PR DESCRIPTION
**Pull request by rektide**
Hello. Wanted to float this, as a way to allow transforms to be async. This unlocks any kind of transform that would want to query some exterior piece of state.

### CODE REVIEW

**Comment by rektide** [comment]
Test failures are on Node v4. This is expected, as v4 does not have async function support.

It is worth noting that Node v4 is end of life in two months.

**Comment by ChiefORZ** [comment]
any updates on merging this PR?

**Comment by maksimsemenov** [comment]
any updates on merging this PR?

**Comment by Daniel15** [comment]
Does this have a performance impact for non-async transforms, if they're running across tens of thousands of files?

**Comment by rektide** [comment]
I don't have any good stress tests to benchmark. :( There will be some impact, yes, but whether it's perceptible is hard to say.

**Comment by foush** [comment]
@Daniel15 any chance we can consider merging this? Would be nice to have async support for more complex codemods

**Comment by Daniel15** [comment]
I'll publish this to npm soon, I just need to figure out who has permission to publish the package. Sorry for the delay @rektide!

**Comment by Daniel15** [comment]
Published as 0.12.0. Thanks for your contribution!

**Pull request merged**
